# Job Recommendation System
## iNetworks task
You are required to build a system to recommend the job functions in which an employee with a specific job title can work.

Basically, given the job title, recommend a job function (and an industry)

### 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### 2. Read data

In [2]:
df = pd.read_csv('jobs_data.csv')
df.head()

title  \
0                 Full Stack PHP Developer   
1  CISCO Collaboration Specialist Engineer   
2            Senior Back End-PHP Developer   
3                              UX Designer   
4                      Java Technical Lead   

                                         jobFunction  \
0  ['Engineering - Telecom/Technology', 'IT/Softw...   
1  ['Installation/Maintenance/Repair', 'IT/Softwa...   
2  ['Engineering - Telecom/Technology', 'IT/Softw...   
3  ['Creative/Design/Art', 'IT/Software Developme...   
4  ['Engineering - Telecom/Technology', 'IT/Softw...   

                                            industry  
0  ['Computer Software', 'Marketing and Advertisi...  
1                ['Information Technology Services']  
2       ['Computer Software', 'Computer Networking']  
3  ['Computer Software', 'Information Technology ...  
4  ['Computer Software', 'Information Technology ...

### 3. Pre-processing 

In [3]:
import ast
vals_jf = []

for val in df["jobFunction"]:
    x = ast.literal_eval(val)
    vals_jf.append(x)

# Convert the vals array into a dataframe
jf_df = pd.DataFrame(data=vals_jf)
jf_df.columns = ['jf_1', 'jf_2', 'jf_3']

# Drop the 'jobFunction' column
df_no_jf = df.drop(columns='jobFunction') 

# concatinate the two DFs
df_new = pd.concat([df_no_jf, jf_df], axis=1)
df_new = df_new.drop_duplicates()
df_new.sort_values(by='title')

title  \
1045                   .NET Backend Developer   
9413                   .NET Backend Developer   
3694   .NET Core Developer - Senior\Team Lead   
10612                          .NET Developer   
1299                           .NET Developer   
...                                       ...   
4507                     مندوب مبيعات - خارجي   
1996                     مندوب مبيعات - خارجي   
2290                     مندوب مبيعات - خارجي   
1668         موظفة نشر و سوشيال ميديا اونلاين   
8514         موظفة نشر و سوشيال ميديا اونلاين   

                                                industry  \
1045                 ['Information Technology Services']   
9413                 ['Information Technology Services']   
3694                 ['Information Technology Services']   
10612                              ['Computer Software']   
1299                               ['Computer Software']   
...                                                  ...   
4507   ['Graphic Design', 'Computer Software', 'Marke...   
1996   ['Computer Software', 'Graphic Design', 'Marke...   
2290   ['Marketing and Advertising', 'Computer Softwa...   
1668                       ['Marketing and Advertising']   
8514                       ['Marketing and Advertising']   

                                   jf_1                              jf_2  \
1045   Engineering - Telecom/Technology           IT/Software Development   
9413            IT/Software Development  Engineering - Telecom/Technology   
3694            IT/Software Development  Engineering - Telecom/Technology   
10612           IT/Software Development  Engineering - Telecom/Technology   
1299   Engineering - Telecom/Technology           IT/Software Development   
...                                 ...                               ...   
4507                       Sales/Retail                              None   
1996                       Sales/Retail                              None   
2290                       Sales/Retail                              None   
1668        Media/Journalism/Publishing          Marketing/PR/Advertising   
8514           Marketing/PR/Advertising       Media/Journalism/Publishing   

       jf_3  
1045   None  
9413   None  
3694   None  
10612  None  
1299   None  
...     ...  
4507   None  
1996   None  
2290   None  
1668   None  
8514   None  

[7518 rows x 5 columns]

In [4]:
vals_ind = []

for val in df["industry"]:
    x = ast.literal_eval(val)
    vals_ind.append(x)

ind_df = pd.DataFrame(data=vals_ind)
ind_df.columns = ['ind_1', 'ind_2', 'ind_3']

df_no_ind = df_new.drop(columns='industry') 

df_final = pd.concat([df_no_ind, ind_df], axis=1)

In [5]:
df_final_drop = df_final.drop_duplicates()
df2 = df_final_drop.fillna('')
df2

title  \
0                               Full Stack PHP Developer   
1                CISCO Collaboration Specialist Engineer   
2                          Senior Back End-PHP Developer   
3                                            UX Designer   
4                                    Java Technical Lead   
...                                                  ...   
10864                               Marketing Specialist   
10865                                                      
10866                  Senior PHP Developer - Alexandria   
10867  Sales & Account Manager (Real Estate / Medical...   
10868  Technical and Network Support Engineer - Alexa...   

                                   jf_1                              jf_2  \
0      Engineering - Telecom/Technology           IT/Software Development   
1       Installation/Maintenance/Repair           IT/Software Development   
2      Engineering - Telecom/Technology           IT/Software Development   
3                   Creative/Design/Art           IT/Software Development   
4      Engineering - Telecom/Technology           IT/Software Development   
...                                 ...                               ...   
10864          Marketing/PR/Advertising       Media/Journalism/Publishing   
10865                                                                       
10866  Engineering - Telecom/Technology           IT/Software Development   
10867              Business Development                      Sales/Retail   
10868   Installation/Maintenance/Repair  Engineering - Telecom/Technology   

                                   jf_3                            ind_1  \
0                                                      Computer Software   
1      Engineering - Telecom/Technology  Information Technology Services   
2                                                      Computer Software   
3                                                      Computer Software   
4                                                      Computer Software   
...                                 ...                              ...   
10864                                          Marketing and Advertising   
10865                                    Real Estate/Property Management   
10866                                    Information Technology Services   
10867          Customer Service/Support  Real Estate/Property Management   
10868           IT/Software Development                Computer Software   

                                     ind_2                            ind_3  
0                Marketing and Advertising                                   
1                                                                            
2                      Computer Networking                                   
3          Information Technology Services                   Computer Games  
4          Information Technology Services                                   
...                                    ...                              ...  
10864  Public Relations and Communications                Computer Software  
10865                        Manufacturing                                   
10866                                                                        
10867                               Retail  Healthcare and Medical Services  
10868                            Education  Healthcare and Medical Services  

[7912 rows x 7 columns]

In [6]:
job_title = "Data Scientist"
result = df2.loc[df2['title'] == job_title, :]
result = result.drop_duplicates()
result

title                     jf_1  \
866   Data Scientist         Analyst/Research   
4500  Data Scientist  IT/Software Development   

                                  jf_2 jf_3              ind_1 ind_2 ind_3  
866   Engineering - Telecom/Technology       Computer Software  FMCG        
4500                  Analyst/Research       Computer Software

### Recommendation System

#### 4.1. Given job title, recommend function

#### Ideas:
   - Combine the 'title', 'ind_1', 'ind_2' and 'ind_3' to one column as a word bag
   - Drop the 'jf_2' and 'jf_3' columns
   - Train the TFIDF on the new column
   - Use it to predict the top 5 jf_1's

In [7]:
# Import TfIdfVectorizer from scikit-learn
from sklearn.feature_extraction.text import TfidfVectorizer

# Define a TF-IDF Vectorizer Object. Remove all english stop words such as 'the', 'a'
tfidf = TfidfVectorizer(stop_words='english')

# Replace NaN with an empty string
df2['title'] = df2['title'].fillna('')

# Construct the required TF-IDF matrix by fitting and transforming the data
tfidf_matrix_title = tfidf.fit_transform(df2['title'])

# Output the shape of tfidf_matrix
tfidf_matrix_title.shape

(7912, 1320)

There are 1320 words used to describe 7912 jobs

In [8]:
# Import linear_kernel
from sklearn.metrics.pairwise import linear_kernel

# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix_title, tfidf_matrix_title)

In [9]:
df2 = df2.reset_index()
df2

index                                              title  \
0         0                           Full Stack PHP Developer   
1         1            CISCO Collaboration Specialist Engineer   
2         2                      Senior Back End-PHP Developer   
3         3                                        UX Designer   
4         4                                Java Technical Lead   
...     ...                                                ...   
7907  10864                               Marketing Specialist   
7908  10865                                                      
7909  10866                  Senior PHP Developer - Alexandria   
7910  10867  Sales & Account Manager (Real Estate / Medical...   
7911  10868  Technical and Network Support Engineer - Alexa...   

                                  jf_1                              jf_2  \
0     Engineering - Telecom/Technology           IT/Software Development   
1      Installation/Maintenance/Repair           IT/Software Development   
2     Engineering - Telecom/Technology           IT/Software Development   
3                  Creative/Design/Art           IT/Software Development   
4     Engineering - Telecom/Technology           IT/Software Development   
...                                ...                               ...   
7907          Marketing/PR/Advertising       Media/Journalism/Publishing   
7908                                                                       
7909  Engineering - Telecom/Technology           IT/Software Development   
7910              Business Development                      Sales/Retail   
7911   Installation/Maintenance/Repair  Engineering - Telecom/Technology   

                                  jf_3                            ind_1  \
0                                                     Computer Software   
1     Engineering - Telecom/Technology  Information Technology Services   
2                                                     Computer Software   
3                                                     Computer Software   
4                                                     Computer Software   
...                                ...                              ...   
7907                                          Marketing and Advertising   
7908                                    Real Estate/Property Management   
7909                                    Information Technology Services   
7910          Customer Service/Support  Real Estate/Property Management   
7911           IT/Software Development                Computer Software   

                                    ind_2                            ind_3  
0               Marketing and Advertising                                   
1                                                                           
2                     Computer Networking                                   
3         Information Technology Services                   Computer Games  
4         Information Technology Services                                   
...                                   ...                              ...  
7907  Public Relations and Communications                Computer Software  
7908                        Manufacturing                                   
7909                                                                        
7910                               Retail  Healthcare and Medical Services  
7911                            Education  Healthcare and Medical Services  

[7912 rows x 8 columns]

In [10]:
# Construct a reverse map of indices and movie titles
indices = pd.Series(df2.index, index=df2['title']).drop_duplicates()

In [11]:
indices

title
Full Stack PHP Developer                                       0
CISCO Collaboration Specialist Engineer                        1
Senior Back End-PHP Developer                                  2
UX Designer                                                    3
Java Technical Lead                                            4
                                                            ... 
Marketing Specialist                                        7907
                                                            7908
Senior PHP Developer - Alexandria                           7909
Sales & Account Manager (Real Estate / Medical) - Assiut    7910
Technical and Network Support Engineer - Alexandria         7911
Length: 7912, dtype: int64

#### We are now in a good position to define our recommendation function. These are the following steps we'll follow :-

- Get the index of the movie given its title.
- Get the list of cosine similarity scores for that particular movie with all movies. Convert it into a list of tuples where the first element is its position and the second is the similarity score.
- Sort the aforementioned list of tuples based on the similarity scores; that is, the second element.
- Get the top 10 elements of this list. Ignore the first element as it refers to self (the movie most similar to a particular movie is the movie itself).
- Return the titles corresponding to the indices of the top elements.

In [12]:
# Function that takes in movie title as input and outputs most similar movies
def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df2['jf_1'].iloc[movie_indices]

In [13]:
get_recommendations('UX Designer')

3                 Creative/Design/Art
2    Engineering - Telecom/Technology
1     Installation/Maintenance/Repair
0    Engineering - Telecom/Technology
Name: jf_1, dtype: object

In [14]:
jobs = ['Marketing Specialist', 'Sales & Account Manager (Real Estate / Medical) - Assiut', 'Marketing Specialist', 'Data Scientist']
for job in jobs:
    print(f"Recommended job functions for job {job}:")
    print(get_recommendations(job), '\n')

Recommended job functions for job Marketing Specialist:
19    Engineering - Telecom/Technology
18                  Accounting/Finance
17             IT/Software Development
16            Marketing/PR/Advertising
15         Media/Journalism/Publishing
14                  Education/Teaching
13             IT/Software Development
12                        Sales/Retail
11                  Accounting/Finance
10                        Sales/Retail
Name: jf_1, dtype: object 

Recommended job functions for job Sales & Account Manager (Real Estate / Medical) - Assiut:
0    Engineering - Telecom/Technology
Name: jf_1, dtype: object 

Recommended job functions for job Marketing Specialist:
19    Engineering - Telecom/Technology
18                  Accounting/Finance
17             IT/Software Development
16            Marketing/PR/Advertising
15         Media/Journalism/Publishing
14                  Education/Teaching
13             IT/Software Development
12                        Sales/Retail


#### 4.2. Given job title, recommend job function and industry

In [63]:
# Define a TF-IDF Vectorizer Object. Remove all english stop words such as 'the', 'a'
tfidf2 = TfidfVectorizer(stop_words='english')

# Re-read the dropped dataframe, because... reasons
df3 = df_final_drop.fillna('')

# Replace NaN with an empty string
df3['title'] = df3['title'].fillna('')

# Construct the required TF-IDF matrix by fitting and transforming the data
tfidf_matrix_title2 = tfidf2.fit_transform(df3['title'])

# Compute the cosine similarity matrix
cosine_sim2 = linear_kernel(tfidf_matrix_title2, tfidf_matrix_title2)

# Reset index
df3 = df3.reset_index()

# Construct a reverse map of indices and movie titles
indices = pd.Series(df3.index, index=df3['title']).drop_duplicates()

In [64]:
df3

index                                              title  \
0         0                           Full Stack PHP Developer   
1         1            CISCO Collaboration Specialist Engineer   
2         2                      Senior Back End-PHP Developer   
3         3                                        UX Designer   
4         4                                Java Technical Lead   
...     ...                                                ...   
7907  10864                               Marketing Specialist   
7908  10865                                                      
7909  10866                  Senior PHP Developer - Alexandria   
7910  10867  Sales & Account Manager (Real Estate / Medical...   
7911  10868  Technical and Network Support Engineer - Alexa...   

                                  jf_1                              jf_2  \
0     Engineering - Telecom/Technology           IT/Software Development   
1      Installation/Maintenance/Repair           IT/Software Development   
2     Engineering - Telecom/Technology           IT/Software Development   
3                  Creative/Design/Art           IT/Software Development   
4     Engineering - Telecom/Technology           IT/Software Development   
...                                ...                               ...   
7907          Marketing/PR/Advertising       Media/Journalism/Publishing   
7908                                                                       
7909  Engineering - Telecom/Technology           IT/Software Development   
7910              Business Development                      Sales/Retail   
7911   Installation/Maintenance/Repair  Engineering - Telecom/Technology   

                                  jf_3                            ind_1  \
0                                                     Computer Software   
1     Engineering - Telecom/Technology  Information Technology Services   
2                                                     Computer Software   
3                                                     Computer Software   
4                                                     Computer Software   
...                                ...                              ...   
7907                                          Marketing and Advertising   
7908                                    Real Estate/Property Management   
7909                                    Information Technology Services   
7910          Customer Service/Support  Real Estate/Property Management   
7911           IT/Software Development                Computer Software   

                                    ind_2                            ind_3  
0               Marketing and Advertising                                   
1                                                                           
2                     Computer Networking                                   
3         Information Technology Services                   Computer Games  
4         Information Technology Services                                   
...                                   ...                              ...  
7907  Public Relations and Communications                Computer Software  
7908                        Manufacturing                                   
7909                                                                        
7910                               Retail  Healthcare and Medical Services  
7911                            Education  Healthcare and Medical Services  

[7912 rows x 8 columns]

In [69]:
# Function that takes in movie title as input and outputs most similar movies
def get_recommendations2(title, cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[0:10]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df3.iloc[movie_indices, 1:]

In [96]:
recommendations = get_recommendations2('CISCO Collaboration Specialist Engineer', cosine_sim2)
recommendations = recommendations.drop_duplicates()
recommendations

title  \
7911  Technical and Network Support Engineer - Alexa...   
7910  Sales & Account Manager (Real Estate / Medical...   
7909                  Senior PHP Developer - Alexandria   
7908                                                      
7907                               Marketing Specialist   
7906                                                      
7905                                      iOS Developer   
7904                          Senior .Net Web Developer   
7903                                        QA Engineer   
7902                                    Sales Executive   

                                  jf_1                              jf_2  \
7911   Installation/Maintenance/Repair  Engineering - Telecom/Technology   
7910              Business Development                      Sales/Retail   
7909  Engineering - Telecom/Technology           IT/Software Development   
7908                                                                       
7907          Marketing/PR/Advertising       Media/Journalism/Publishing   
7906                                                                       
7905           IT/Software Development  Engineering - Telecom/Technology   
7904           IT/Software Development  Engineering - Telecom/Technology   
7903           IT/Software Development                           Quality   
7902                      Sales/Retail                                     

                          jf_3                            ind_1  \
7911   IT/Software Development                Computer Software   
7910  Customer Service/Support  Real Estate/Property Management   
7909                            Information Technology Services   
7908                            Real Estate/Property Management   
7907                                  Marketing and Advertising   
7906                                  Marketing and Advertising   
7905                                          Computer Software   
7904                                          Computer Software   
7903                                       Engineering Services   
7902                            Information Technology Services   

                                    ind_2                            ind_3  
7911                            Education  Healthcare and Medical Services  
7910                               Retail  Healthcare and Medical Services  
7909                                                                        
7908                        Manufacturing                                   
7907  Public Relations and Communications                Computer Software  
7906                            Furniture                                   
7905      Information Technology Services                                   
7904                                                                        
7903                    Computer Software                                   
7902         Translation and Localization                     Online Media

In [118]:
# Get all job functions 
recommended_job_functions = [recommendations[funs].to_list() for funs in ['jf_1', 'jf_2', 'jf_3']]    # This is a 2D list

# Convert the 2D list into 1D
str_list = sum(recommended_job_functions, [])

# Filter out the empty strings
str_list = list(filter(None, str_list))
str_list

['Installation/Maintenance/Repair',
 'Business Development',
 'Engineering - Telecom/Technology',
 'Marketing/PR/Advertising',
 'IT/Software Development',
 'IT/Software Development',
 'IT/Software Development',
 'Sales/Retail',
 'Engineering - Telecom/Technology',
 'Sales/Retail',
 'IT/Software Development',
 'Media/Journalism/Publishing',
 'Engineering - Telecom/Technology',
 'Engineering - Telecom/Technology',
 'Quality',
 'IT/Software Development',
 'Customer Service/Support']

In [144]:
def get_recs(title, cosine_sim):
    # Initialize variables
    rec_dict = {}   # recommendations dictionary
    
    # Get recommendations
    recommendations = get_recommendations2(title, cosine_sim)
    recommendations = recommendations.drop_duplicates()
    
    # Append all job titles to the 'titles' section in the recommendations dictionary    
    recommended_job_titles = [recommendations['title'].to_list()]
    title_list = sum(recommended_job_titles, [title])
    title_list = list(filter(None, title_list))
    rec_dict['titles'] = title_list
    
    # Append all job functions to the 'functions' section in the recommendations dictionary
    recommended_job_functions = [recommendations[fun].to_list() for fun in ['jf_1', 'jf_2', 'jf_3']] 
    fun_list = sum(recommended_job_functions, [])
    fun_list = list(filter(None, fun_list))
    rec_dict['functions'] = fun_list
    
    
    # Append all job industries to the 'industries' section in the recommendations dictionary
    recommended_job_industries = [recommendations[ind].to_list() for ind in ['ind_1', 'ind_2', 'ind_3']] 
    ind_list = sum(recommended_job_industries, [])
    ind_list = list(filter(None, ind_list))
    rec_dict['industries'] = ind_list
    
    # Return the recommendations dictionary
    return rec_dict

In [145]:
get_recs('CISCO Collaboration Specialist Engineer', cosine_sim2)

{'titles': ['CISCO Collaboration Specialist Engineer',
  'Technical and Network Support Engineer - Alexandria',
  'Sales & Account Manager (Real Estate / Medical) - Assiut',
  'Senior PHP Developer - Alexandria',
  'Marketing Specialist',
  'iOS Developer',
  'Senior .Net Web Developer',
  'QA Engineer',
  'Sales Executive'],
 'functions': ['Installation/Maintenance/Repair',
  'Business Development',
  'Engineering - Telecom/Technology',
  'Marketing/PR/Advertising',
  'IT/Software Development',
  'IT/Software Development',
  'IT/Software Development',
  'Sales/Retail',
  'Engineering - Telecom/Technology',
  'Sales/Retail',
  'IT/Software Development',
  'Media/Journalism/Publishing',
  'Engineering - Telecom/Technology',
  'Engineering - Telecom/Technology',
  'Quality',
  'IT/Software Development',
  'Customer Service/Support'],
 'industries': ['Computer Software',
  'Real Estate/Property Management',
  'Information Technology Services',
  'Real Estate/Property Management',
  'Marke

#### 4.2. but with functions

In [201]:
def preprocess_jf(df):
    vals_jf = []

    for val in df["jobFunction"]:
        x = ast.literal_eval(val)
        vals_jf.append(x)

    # Convert the vals array into a dataframe
    jf_df = pd.DataFrame(data=vals_jf)
    jf_df.columns = ['jf_1', 'jf_2', 'jf_3']

    # Drop the 'jobFunction' column
    df_no_jf = df.drop(columns='jobFunction') 

    # concatinate the two DFs
    df_new = pd.concat([df_no_jf, jf_df], axis=1)
#     df_new = df_new.drop_duplicates()
    df_new.sort_values(by='title')
    
    return df_new

In [202]:
def preprocess_ind(df):
    vals_ind = []

    for val in df["industry"]:
        x = ast.literal_eval(val)
        vals_ind.append(x)

    ind_df = pd.DataFrame(data=vals_ind)
    
    ind_df.columns = ['ind_1', 'ind_2', 'ind_3']
    df_no_ind = df.drop(columns='industry') 
    df_final = pd.concat([df_no_ind, ind_df], axis=1)
    
    return df_final

In [203]:
def preprocess_df(df):
    df_pp = preprocess_jf(df)
    df_final = preprocess_ind(df_pp)
    df_final_drop = df_final.drop_duplicates()
    df2 = df_final_drop.fillna('')
    
    return df2

In [204]:
def init_title(df):
    # Preprocess dataframe
    df_dropped = preprocess_df(df)
    
    # Define a TF-IDF Vectorizer Object. Remove all english stop words such as 'the', 'a'
    tfidf = TfidfVectorizer(stop_words='english')

    # Re-read the dropped dataframe, because... reasons
    df = df_dropped.fillna('')

    # Replace NaN with an empty string
    df['title'] = df['title'].fillna('')

    # Construct the required TF-IDF matrix by fitting and transforming the data
    tfidf_matrix_title = tfidf.fit_transform(df['title'])

    # Compute the cosine similarity matrix
    cosine_sim = linear_kernel(tfidf_matrix_title, tfidf_matrix_title)

    # Reset index
    df = df.reset_index()

    # Construct a reverse map of indices and movie titles
    indices = pd.Series(df.index, index=df['title']).drop_duplicates()
    
    return df_dropped, indices, cosine_sim

In [205]:
# Function that takes in movie title as input and outputs most similar movies
def get_recommendations3(df, title):
    # Get indices and cosine similarity
    df_dropped, indices, cosine_sim = init_title(df)
    
    # Get the index of the job that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all jobs with that job
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the jobs based on the similarity scores
    sim_scores = sorted(sim_scores, reverse=True)

    # Get the scores of the 10 most similar jobs
    sim_scores = sim_scores[0:10]

    # Get the jobs indices
    rec_jobs_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar job functions and industries
    recommendations = df_dropped.iloc[rec_jobs_indices, :]
    
    print("RECOMMENDATIONS: ")
    display(recommendations)
    
    return recommendations

In [206]:
# Get recommendations in form of a dictionary
def get_recs2(df, title):
    # Initialize variables
    rec_dict = {}   # recommendations dictionary
    
    # Get recommendations
    recommendations = get_recommendations3(df, title)
    recommendations = recommendations.drop_duplicates()
    
    # Append all job titles to the 'titles' section in the recommendations dictionary    
    recommended_job_titles = [recommendations['title'].to_list()]
    title_list = sum(recommended_job_titles, [title])
    title_list = list(filter(None, title_list))
    rec_dict['titles'] = title_list
    
    # Append all job functions to the 'functions' section in the recommendations dictionary
    recommended_job_functions = [recommendations[fun].to_list() for fun in ['jf_1', 'jf_2', 'jf_3']] 
    fun_list = sum(recommended_job_functions, [])
    fun_list = list(filter(None, fun_list))
    rec_dict['functions'] = fun_list
    
    
    # Append all job industries to the 'industries' section in the recommendations dictionary
    recommended_job_industries = [recommendations[ind].to_list() for ind in ['ind_1', 'ind_2', 'ind_3']] 
    ind_list = sum(recommended_job_industries, [])
    ind_list = list(filter(None, ind_list))
    rec_dict['industries'] = ind_list
    
    # Return the recommendations dictionary
    return rec_dict

In [207]:
get_recs2(df, 'CISCO Collaboration Specialist Engineer')

RECOMMENDATIONS: 


title  \
10868  Technical and Network Support Engineer - Alexa...   
10867  Sales & Account Manager (Real Estate / Medical...   
10866                  Senior PHP Developer - Alexandria   
10864                               Marketing Specialist   
10861                                      iOS Developer   
10856                          Senior .Net Web Developer   
10855                                        QA Engineer   
10853                                    Sales Executive   
10851          Outdoor Sales Representative - Alexandria   
10850                         Senior Marketing Executive   

                                   jf_1                              jf_2  \
10868   Installation/Maintenance/Repair  Engineering - Telecom/Technology   
10867              Business Development                      Sales/Retail   
10866  Engineering - Telecom/Technology           IT/Software Development   
10864          Marketing/PR/Advertising       Media/Journalism/Publishing   
10861           IT/Software Development  Engineering - Telecom/Technology   
10856           IT/Software Development  Engineering - Telecom/Technology   
10855           IT/Software Development                           Quality   
10853                      Sales/Retail                                     
10851          Customer Service/Support                      Sales/Retail   
10850          Marketing/PR/Advertising       Media/Journalism/Publishing   

                           jf_3                            ind_1  \
10868   IT/Software Development                Computer Software   
10867  Customer Service/Support  Real Estate/Property Management   
10866                            Information Technology Services   
10864                                  Marketing and Advertising   
10861                                          Computer Software   
10856                                          Computer Software   
10855                                       Engineering Services   
10853                            Information Technology Services   
10851                                             Graphic Design   
10850                                  Marketing and Advertising   

                                     ind_2                            ind_3  
10868                            Education  Healthcare and Medical Services  
10867                               Retail  Healthcare and Medical Services  
10866                                                                        
10864  Public Relations and Communications                Computer Software  
10861      Information Technology Services                                   
10856                                                                        
10855                    Computer Software                                   
10853         Translation and Localization                     Online Media  
10851                    Computer Software        Marketing and Advertising  
10850      Real Estate/Property Management

{'titles': ['CISCO Collaboration Specialist Engineer',
  'Technical and Network Support Engineer - Alexandria',
  'Sales & Account Manager (Real Estate / Medical) - Assiut',
  'Senior PHP Developer - Alexandria',
  'Marketing Specialist',
  'iOS Developer',
  'Senior .Net Web Developer',
  'QA Engineer',
  'Sales Executive',
  'Outdoor Sales Representative - Alexandria',
  'Senior Marketing Executive'],
 'functions': ['Installation/Maintenance/Repair',
  'Business Development',
  'Engineering - Telecom/Technology',
  'Marketing/PR/Advertising',
  'IT/Software Development',
  'IT/Software Development',
  'IT/Software Development',
  'Sales/Retail',
  'Customer Service/Support',
  'Marketing/PR/Advertising',
  'Engineering - Telecom/Technology',
  'Sales/Retail',
  'IT/Software Development',
  'Media/Journalism/Publishing',
  'Engineering - Telecom/Technology',
  'Engineering - Telecom/Technology',
  'Quality',
  'Sales/Retail',
  'Media/Journalism/Publishing',
  'IT/Software Development